#+STARTUP: showall

#+TITLE:     Exercise 3
#+AUTHOR:    Paul Gribble
#+EMAIL:     paul@gribblelab.org
#+DATE:      fall 2014
#+OPTIONS: toc:nil html:t num:nil h:1
#+LINK_UP: http://www.gribblelab.org/scicomp/exercises.html
#+LINK_HOME: http://www.gribblelab.org/scicomp/index.html

* cooking the perfect egg
As an egg cooks, the proteins first denature and then coagulate. When
the temperature exceeds a critical point, reactions begin and proceed
faster as the temperature increases. In the egg white the proteins
start to coagulate for temperatures above 63 C, while in the yolk the
proteins start to coagulate for temperatures above 70 C. For a
soft-boiled egg, the white needs to have been heated long enough to
coagulate at a temperature above 63 C, but the yolk should not be
heated above 70 C. For a hard-boiled egg, the centre of the yolk
should be allowed to reach 70 C.

The following equation gives the time $t$ it takes (in seconds) for
the centre of the yolk to reach the temperature $T_{y}$ (Celsius):

\begin{equation}
t = \frac{M^{2/3} c \rho^{1/3}}{K \pi^{2}(4\pi/3)^{2/3}} \ln \left[ 0.76 \frac{T_{o}-T_{w}}{T_{y}-T_{w}} \right]
\end{equation}

where $M$, $\rho$, $c$ and $K$ are properties of the egg: $M$ is mass,
$\rho$ is the density, $c$ is the specific heat capacity, and $K$ is
the thermal conductivity. Relevant values are $M=47$ g for a small egg
and $M=67$ g for a large egg, $\rho=1.038$ g cm$^{-3}$, $c=3.7$ J
g$^{-1}$ K$^{-1}$, and $K=0.0054$ W cm$^{-1}$ K$^{-1}$. The parameter
$T_{w}$ is the temperature (in Celsius) of the boiling water, and
$T_{o}$ is the original temperature of the egg before being put in the
water.

Implement the equation in a program, set $T_{w}=100$ C and $T_{y}=70$
C, and compute $t$ for a large egg taken from the fridge ($T_{o}=4$ C)
and from room temperature ($T_{o}=20$ C).

Test your program with this example:

#+BEGIN_SRC example
Is the egg large (1) or small (0)? 1
enter the initial temperature of the egg
reminder 4.0 for fridge, 20.0 for room: 15.0
time taken to cook the egg is: 342.271 seconds (5 minutes, 42 seconds)
#+END_SRC

[[file:e03sol.html][solutions]]
